name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      select_device:
        description: 'Select :'
        required: true
        type: choice
        options:
        - 'moonstone'

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-latest
    env:
      DEVICE: ${{ github.event.inputs.select_device }}
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
    - uses: actions/checkout@v4

    - name: Prepare environment
      run: |
        grep -v -E "^#|^\n" config.env | sed 's/ #.*//; s/#.*//' >> $GITHUB_ENV

    - name: Set swap to 10G
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup kernel build environment
      run: |
        echo "BUILD_TIME=$(TZ=UTC date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses6 libncurses-dev libsdl1.2-dev libssl-dev libwxgtk3.2-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
        mkdir -p $GITHUB_WORKSPACE/kernel_builder

    - name: Download Clang
      run: |
        cd $GITHUB_WORKSPACE/kernel_builder
        wget -nv -O clang.tar.gz ${{ env.CLANG_SOURCE }}
        mkdir clang
        tar -C clang/ -zxvf clang.tar.gz
        rm clang.tar.gz

    - name: Download kernel source
      run: |
        cd $GITHUB_WORKSPACE/kernel_builder
        git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} stone-kernel --depth=1

    - name: Build kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_builder/stone-kernel
        export PATH=$GITHUB_WORKSPACE/kernel_builder/clang/bin:$PATH
        export KBUILD_BUILD_HOST=Github-Action
        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
        make -j$(nproc --all) CC=clang O=out ARCH=${{ env.KERNEL_ARCH }} ${{ env.EXTRA_CMDS }} ${DEVICE}_defconfig
        make -j$(nproc --all) CC=clang O=out ARCH=${{ env.KERNEL_ARCH }} ${{ env.EXTRA_CMDS }}

    - name: Check a kernel output files
      run: |
       cd $GITHUB_WORKSPACE/kernel_builder
       if [ -f stone-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }} ]; then
           echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
       else
           echo "Kernel output file is empty"
           exit 1
       fi
       if [ -f stone-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/dtb.img ]; then
            echo "CHECK_DTB_IS_OK=true" >> $GITHUB_ENV
       else
            echo "DTB image is empty"
            exit 1
       fi

    - name: Get Modules
      if: env.CHECK_FILE_IS_OK == 'true'
      run: |
        cd $GITHUB_WORKSPACE/kernel_builder/stone-kernel
        mkdir -p modules
        find out -name "*.ko" -exec cp {} modules/ \;

    - name: Upload kernel image
      if: env.CHECK_FILE_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_IMAGE_NAME }}${{ env.LOCALVERSION }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
        path: kernel_builder/stone-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/${{ env.KERNEL_IMAGE_NAME }}

    - name: Upload DTB image
      if: env.CHECK_DTB_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: dtb-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
        path: kernel_builder/stone-kernel/out/arch/${{ env.KERNEL_ARCH }}/boot/dtb.img

    - name: Upload Modules
      if: env.CHECK_FILE_IS_OK == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: modules-${{ env.DEVICE }}
        path: kernel_builder/stone-kernel/modules/*
